# SPDX-License-Identifier: GPL-2.0

qnoc-msm8916-objs			:= msm8916.o
qnoc-msm8916-stress-objs		:= msm8916-stress.o
qnoc-msm8974-objs			:= msm8974.o
qnoc-qcs404-objs			:= qcs404.o
qnoc-sdm845-objs			:= sdm845.o
qnoc-sdm845-stress-objs			:= sdm845-stress.o
icc-bcm-voter-objs			:= bcm-voter.o
icc-osm-l3-objs				:= osm-l3.o
icc-smd-rpm-objs			:= smd-rpm.o
icc-rpmh-obj				:= icc-rpmh.o

obj-$(CONFIG_INTERCONNECT_QCOM_BCM_VOTER) += icc-bcm-voter.o
obj-$(CONFIG_INTERCONNECT_QCOM_MSM8916) += qnoc-msm8916.o
obj-$(CONFIG_INTERCONNECT_QCOM_MSM8916_STRESS) += qnoc-msm8916-stress.o
obj-$(CONFIG_INTERCONNECT_QCOM_MSM8974) += qnoc-msm8974.o
obj-$(CONFIG_INTERCONNECT_QCOM_OSM_L3) += icc-osm-l3.o
obj-$(CONFIG_INTERCONNECT_QCOM_QCS404) += qnoc-qcs404.o
obj-$(CONFIG_INTERCONNECT_QCOM_RPMH) += icc-rpmh.o
obj-$(CONFIG_INTERCONNECT_QCOM_SDM845) += qnoc-sdm845.o
obj-$(CONFIG_INTERCONNECT_QCOM_SDM845_STRESS) += qnoc-sdm845-stress.o
obj-$(CONFIG_INTERCONNECT_QCOM_SMD_RPM) += icc-smd-rpm.o
